import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";


const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} font-sans antialiased bg-gradient-to-br from-blue-100 via-white to-pink-100`}>
        <div className="flex min-h-screen">
        
          <div className="flex-1 flex flex-col min-h-screen">
          
            <main className="flex-1">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
